language: ruby
bundler_args: "--without development:production"
cache: bundler
sudo: false
script: bundle exec rspec
rvm:
- 2.1.5
notifications:
  webhooks: http://cfa-project-monitor.herokuapp.com/projects/67f80d53-afb0-4344-bd40-2644f55a4462/status
env:
  global:
  - S3_BUCKET_NAME=gems-for-travis
  - OHANA_API_ENDPOINT=http://ohana-api-test.herokuapp.com/api
  - DOMAIN_NAME=lvh.me
  - secure: TbS1XZyUYTYm9YjW2ATWk8LHaVwWQO5Onm81hkWM/FZasUfk2gbVOMuXTag+2Wif5cBd2dhVFaLZmROdqaXk1U52m/s6snfWNqJa1olEA0GEWFLwimvouAsUpl4JB1jKTiIN81MUdBv4espLYD/f5sbM5/a4ZoYPUXutfI+YItg=
