files: ['**/*.js'] # No need to put app/assets/ or vendor/assets here
exclude_paths: ['vendor/assets/javascripts']
options:
  bitwise:        false
  camelcase:      false
  curly:          false
  eqeqeq:         true
  es3:            true
  forin:          true
  immed:          true
  indent:         2
  latedef:        true
  newcap:         true
  noarg:          true
  noempty:        true
  nonew:          true
  plusplus:       false
  quotmark:       true
  undef:          true
  unused:         true
  strict:         true
  maxparams:      5
  maxdepth:       5
  maxstatements:  25
  maxcomplexity:  10
  maxlen:         80
  browser:        true
  devel:          true
  globals:
    jQuery:       true
    '$':          true
    define:       true
    require:      true
    requirejs:    true
    google:       true
